VALIDATION_DATASET_SIZE = 10
DATASET_SIZE = 100
DATASET_PATH = '/training'
TRAINING_IMAGE_SIZE = VALIDATION_IMAGE_SIZE = (128,128,6)
TRAINING_BATCH_SIZE = 3
VALIDATION_BATCH_SIZE = 3
NUMBER_OF_CHANNELS = 1
SHUFFLE_DATA = True
TRANSFORM = True
BATCH_SIZE = 10
CLASSES = 5
LEARNING_RATE = 0.01
PRETRAINED_WEIGHTS = None
NBR_CLASSES = 4
NBR_EPOCH = 20