VALIDATION_DATASET_SIZE = 10
DATASET_SIZE = 100
DATASET_PATH = './../data/training'
TRAINING_IMAGE_SIZE = VALIDATION_IMAGE_SIZE = (128,128,6)
TRAINING_BATCH_SIZE = 3
VALIDATION_BATCH_SIZE = 3
NUMBER_OF_CHANNELS = 1
SHUFFLE_DATA = True
TRANSFORM = True
BATCH_SIZE = 10
CLASSES = 4
LEARNING_RATE = 0.05
PRETRAINED_WEIGHTS = None
NBR_CLASSES = 4
NBR_EPOCH = 50
DIVISIBILITY_FACTOR = 16
CHECKPOINT_PATH = './../models/try_3/my_checkpoint.ckpt'